version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2
workflows:
  build:
    jobs:
        - cypress/install
        - cypress/run --record:
            requires: 
              - cypress/install
            store_artifacts: true
            parallel:
            parallelism: 2 
            group: 2 machines












 # start-command: npm start
 # cypress-command: 'npx cypress run --record --parallel'