version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --parallel --record
          parallelism: 2
          start-command: npm run start

# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@2.2.0
# workflows:
#   build:
#     jobs:
#         - cypress/install
#         - cypress/run:
#             requires: 
#               - cypress/install
#             store_artifacts: true
#             spec: cypress/e2e/T1.cy.js
#         - cypress/run:
#             requires: 
#               - cypress/install
#             store_artifacts: true
#             spec: cypress/e2e/T2.cy.js
#             parallel: true
#             parallelism: 2 













 # start-command: npm start
 # cypress-command: 'npx cypress run --record --parallel'